[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
raydium_cp_swap_customize = "F4tHwxNDizBtYz4s5rSukS32RY4VA1AYSHjBmywRCcTp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
